import type { ScenarioData } from './types';

export const SCENARIOS: Record<'pess' | 'base' | 'opt', ScenarioData> = {
  base: {
    kpis: [
      {
        title: 'Свободные деньги',
        value: 1_850_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'green' : 'red'),
        trend: { value: 29.7, unit: '%', direction: 'up' },
      },
      {
        title: 'Невыбранные лимиты',
        value: 1_600_000,
        unit: '₽',
        colorRule: () => 'blue',
        trend: { value: 0, unit: '%', direction: 'none' },
      },
      {
        title: 'Буфер ликвидности',
        value: 120,
        unit: 'дней',
        colorRule: (v) => (v >= 90 ? 'green' : 'red'),
        trend: { value: 4, unit: 'д', direction: 'down' },
      },
      {
        title: 'Чистый долг',
        value: 5_800_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'red' : 'green'),
        trend: { value: 19.4, unit: '%', direction: 'down' },
      },
      {
        title: 'CCC',
        value: 45,
        unit: 'дней',
        colorRule: (v) => (v > 40 ? 'red' : 'green'),
        trend: { value: 12, unit: 'д', direction: 'up' },
      },
      {
        title: 'Покрытие долгов',
        value: 5.2,
        unit: '×',
        colorRule: (v) => (v >= 2 ? 'green' : 'red'),
        trend: { value: 2.5, unit: 'x', direction: 'up' },
      },
    ],
    ebitdaPercent: 18.2,
    ebitdaSeries: {
      '12 июн.': 17.5,
      '12 авг.': 18.0,
      '12 окт.': 18.0,
      '12 нояб.': 17.8,
      '12 дек.': 18.5,
    },
    ocfToEbitdaBadge: 'OCF/EBITDA: 0.82x',
    ebitdaDetail: {
      title: 'Выше',
      amount: 'На 2.5%',
      details: 'Относительно пессимистичного сценария',
    },

    netProfitChange: '+28% (2.2M)',
    netProfitBars: [
      { date: '12 июн.', values: [{ value: 120_000 }] },
      { date: '13 июн.', values: [{ value: 118_000 }] },
      { date: '14 июн.', values: [{ value: 121_500 }] },
      { date: '15 июн.', values: [{ value: 115_000 }] },
      { date: '16 июн.', values: [{ value: 119_000 }] },
      { date: '17 июн.', values: [{ value: 122_000 }] },
      { date: '18 июн.', values: [{ value: 120_000 }] },
    ],
    netProfitDetail: {
      title: 'Выше',
      amount: 'На 35.1%',
      details: 'Относительно стандартного сценария',
    },
  },

  pess: {
    kpis: [
      {
        title: 'Свободные деньги',
        value: 1_200_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'green' : 'red'),
        trend: { value: 12, unit: '%', direction: 'down' },
      },
      {
        title: 'Невыбранные лимиты',
        value: 1_000_000,
        unit: '₽',
        colorRule: () => 'blue',
        trend: { value: 0, unit: '%', direction: 'none' },
      },
      {
        title: 'Буфер ликвидности',
        value: 80,
        unit: 'дней',
        colorRule: (v) => (v >= 90 ? 'green' : 'red'),
        trend: { value: 8, unit: 'д', direction: 'down' },
      },
      {
        title: 'Чистый долг',
        value: 7_000_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'red' : 'green'),
        trend: { value: 6.5, unit: '%', direction: 'up' },
      },
      {
        title: 'CCC',
        value: 60,
        unit: 'дней',
        colorRule: (v) => (v > 40 ? 'red' : 'green'),
        trend: { value: 7, unit: 'д', direction: 'up' },
      },
      {
        title: 'Покрытие долгов',
        value: 3.1,
        unit: '×',
        colorRule: (v) => (v >= 2 ? 'green' : 'red'),
        trend: { value: 0.6, unit: 'x', direction: 'down' },
      },
    ],
    ebitdaPercent: 16.4,
    ebitdaSeries: {
      '12 июн.': 15.5,
      '12 авг.': 16.0,
      '12 окт.': 16.3,
      '12 нояб.': 15.8,
      '12 дек.': 16.5,
    },
    ocfToEbitdaBadge: 'OCF/EBITDA: 0.65x',
    ebitdaDetail: {
      title: 'Ниже',
      amount: 'На 3.1%',
      details: 'Относительно стандартного сценария',
    },

    netProfitChange: '-12% (−0.6M)',
    netProfitBars: [
      { date: '12 июн.', values: [{ value: 100_000 }] },
      { date: '13 июн.', values: [{ value: 98_000 }] },
      { date: '14 июн.', values: [{ value: 102_000 }] },
      { date: '15 июн.', values: [{ value: 95_000 }] },
      { date: '16 июн.', values: [{ value: 99_000 }] },
      { date: '17 июн.', values: [{ value: 101_000 }] },
      { date: '18 июн.', values: [{ value: 98_500 }] },
    ],
    netProfitDetail: {
      title: 'Ниже',
      amount: 'На 14.8%',
      details: 'Относительно стандартного сценария',
    },
  },

  opt: {
    kpis: [
      {
        title: 'Свободные деньги',
        value: 2_300_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'green' : 'red'),
        trend: { value: 41, unit: '%', direction: 'up' },
      },
      {
        title: 'Невыбранные лимиты',
        value: 2_000_000,
        unit: '₽',
        colorRule: () => 'blue',
        trend: { value: 0, unit: '%', direction: 'none' },
      },
      {
        title: 'Буфер ликвидности',
        value: 150,
        unit: 'дней',
        colorRule: (v) => (v >= 90 ? 'green' : 'red'),
        trend: { value: 10, unit: 'д', direction: 'up' },
      },
      {
        title: 'Чистый долг',
        value: 4_500_000,
        unit: '₽',
        colorRule: (v) => (v > 0 ? 'red' : 'green'),
        trend: { value: 25, unit: '%', direction: 'down' },
      },
      {
        title: 'CCC',
        value: 35,
        unit: 'дней',
        colorRule: (v) => (v > 40 ? 'red' : 'green'),
        trend: { value: 5, unit: 'д', direction: 'down' },
      },
      {
        title: 'Покрытие долгов',
        value: 6.8,
        unit: '×',
        colorRule: (v) => (v >= 2 ? 'green' : 'red'),
        trend: { value: 3.1, unit: 'x', direction: 'up' },
      },
    ],
    ebitdaPercent: 20.5,
    ebitdaSeries: {
      '12 июн.': 18.5,
      '12 авг.': 19.0,
      '12 окт.': 19.5,
      '12 нояб.': 20.0,
      '12 дек.': 20.5,
    },
    ocfToEbitdaBadge: 'OCF/EBITDA: 0.95x',
    ebitdaDetail: {
      title: 'Выше',
      amount: 'На 6.8%',
      details: 'Относительно стандартного сценария',
    },

    netProfitChange: '+42% (3.1M)',
    netProfitBars: [
      { date: '12 июн.', values: [{ value: 125_000 }] },
      { date: '13 июн.', values: [{ value: 127_000 }] },
      { date: '14 июн.', values: [{ value: 130_000 }] },
      { date: '15 июн.', values: [{ value: 128_000 }] },
      { date: '16 июн.', values: [{ value: 132_000 }] },
      { date: '17 июн.', values: [{ value: 135_000 }] },
      { date: '18 июн.', values: [{ value: 133_000 }] },
    ],
    netProfitDetail: {
      title: 'Выше',
      amount: 'На 48.6%',
      details: 'Относительно стандартного сценария',
    },
  },
};
