import type { Payment } from './types';

export const paymentsMock: Payment[] = [
  {
    id: '1',
    date: '2025-01-20',
    description: 'Выплата заработной платы сотрудникам',
    org: 'ООО "Основная компания"',
    bank: 'Сбербанк',
    category: 'Зарплаты',
    amount: 1_500_000,
    recipient: 'Сотрудники',
    status: 'done',
  },
  {
    id: '2',
    date: '2025-01-20',
    description: 'Выплата заработной платы сотрудникам',
    org: 'ООО "Основная компания"',
    bank: 'Сбербанк',
    category: 'Зарплаты',
    amount: 1_500_000,
    recipient: 'Сотрудники',
    status: 'pending',
  },
  {
    id: '3',
    date: '2025-01-20',
    description: 'Выплата заработной платы сотрудникам',
    org: 'ООО "Основная компания"',
    bank: 'Сбербанк',
    category: 'Зарплаты',
    amount: 1_500_000,
    recipient: 'Сотрудники',
    status: 'error',
  },
  {
    id: '4',
    date: '2025-01-19',
    description: 'Перечисление налогов',
    org: 'ООО "Второе юрлицо"',
    bank: 'Альфа',
    category: 'Налоги',
    amount: 630_000,
    recipient: 'ФНС',
    status: 'done',
  },
  {
    id: '5',
    date: '2025-01-18',
    description: 'Платеж по лизингу оборудования',
    org: 'ООО "Второе юрлицо"',
    bank: 'Сбербанк',
    category: 'Лизинг',
    amount: 220_000,
    recipient: 'Лизинговая компания',
    status: 'done',
  },
  {
    id: '6',
    date: '2025-01-18',
    description: 'Оплата консультационных услуг',
    org: 'ООО "Третье юрлицо"',
    bank: 'Тинькофф',
    category: 'Другое',
    amount: 130_000,
    recipient: 'Поставщик',
    status: 'pending',
  },
];
